import { useMemo, useState } from 'react';
import { DragDropContext, Draggable, Droppable } from 'react-beautiful-dnd';
import { Bar, BarChart, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Badge, Button, Card } from '../components/UI';
import { alerts, crewMembers, kpis, utilizationTrend } from '../data/mockData';

const statusTone = { 'On Duty': 'green', Standby: 'yellow', 'On Leave': 'red' };

export function Dashboard() { return <div className='grid gap-4 lg:grid-cols-4'>{kpis.map((k)=><Card key={k.title} className='p-4'><p className='text-xs text-slate-400'>{k.title}</p><p className='mt-2 text-2xl font-bold'>{k.value}</p><p className='text-xs text-cyan-300'>{k.delta} · {k.subtitle}</p></Card>)}<Card className='p-4 lg:col-span-2 h-80'><h3 className='mb-3 font-semibold'>Crew Utilization Trend</h3><ResponsiveContainer width='100%' height='90%'><LineChart data={utilizationTrend}><XAxis dataKey='day'/><YAxis/><Tooltip/><Line dataKey='utilization' stroke='#22d3ee' strokeWidth={2}/></LineChart></ResponsiveContainer></Card><Card className='p-4 lg:col-span-2 h-80'><h3 className='mb-3 font-semibold'>Total Duty Hours</h3><ResponsiveContainer width='100%' height='90%'><BarChart data={utilizationTrend}><XAxis dataKey='day'/><YAxis/><Tooltip/><Bar dataKey='dutyHours' fill='#0ea5e9'/></BarChart></ResponsiveContainer></Card></div>; }

export function CrewPage(){const [query,setQuery]=useState(''); const filtered=useMemo(()=>crewMembers.filter((c)=>`${c.name} ${c.role} ${c.base}`.toLowerCase().includes(query.toLowerCase())),[query]); return <><div className='mb-4 flex flex-wrap gap-2'><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder='Search by crew name, role, or base' className='w-full max-w-md rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm'/><Button variant='secondary'>Filter: All Bases</Button></div><div className='grid gap-4 md:grid-cols-2 xl:grid-cols-3'>{filtered.map((c)=><Card key={c.id} className='p-4'><div className='flex items-center gap-3'><img src={c.avatar} className='h-14 w-14 rounded-full'/><div><h4 className='font-semibold'>{c.name}</h4><p className='text-xs text-slate-400'>{c.role} · {c.base} · {c.id}</p></div></div><div className='mt-3 flex items-center justify-between'><Badge tone={statusTone[c.status]}>{c.status}</Badge><Button variant='ghost'>Open Profile</Button></div></Card>)}</div></>;}

export function RosterPage(){return <Card className='p-4'><h3 className='font-semibold'>Weekly Roster Matrix</h3><div className='mt-4 grid grid-cols-8 gap-2 text-xs'>{['Crew','Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((h)=><div key={h} className='font-semibold text-cyan-300'>{h}</div>)}{crewMembers.map((c)=><><div key={`${c.id}-name`} className='rounded bg-slate-800 p-2'>{c.name}</div>{Array.from({length:7}).map((_,i)=><div key={`${c.id}-${i}`} className={`rounded p-2 ${i%3===0?'bg-cyan-500/30':i%3===1?'bg-emerald-500/30':'bg-violet-500/30'}`}>{['AM','PM','OFF'][i%3]}</div>)}</>)}</div></Card>}

export function DutyHoursPage(){return <Card className='p-4'><h3 className='font-semibold'>Duty Hours Tracker</h3><div className='space-y-4 mt-4'>{crewMembers.map((c)=>{const level=c.hours>90?'red':c.hours>80?'yellow':'green';const label=c.hours>90?'Overlimit':c.hours>80?'Warning':'Safe';return <div key={c.id}><div className='mb-1 flex justify-between text-sm'><span>{c.name}</span><Badge tone={level}>{label} · {c.hours}h</Badge></div><div className='h-2 rounded bg-slate-800'><div style={{width:`${c.hours}%`}} className={`h-2 rounded ${level==='green'?'bg-emerald-400':level==='yellow'?'bg-amber-400':'bg-red-400'}`}/></div></div>})}</div></Card>}

export function LeavePage(){return <div className='grid gap-4 xl:grid-cols-2'><Card className='p-4'><h3 className='font-semibold'>Leave Request Form</h3><div className='mt-3 space-y-3'><input className='w-full rounded-xl border border-slate-700 bg-slate-900 p-2 text-sm' placeholder='Crew ID'/><input type='date' className='w-full rounded-xl border border-slate-700 bg-slate-900 p-2 text-sm'/><textarea rows='4' className='w-full rounded-xl border border-slate-700 bg-slate-900 p-2 text-sm' placeholder='Request details'></textarea><Button>Submit Request</Button></div></Card><Card className='p-4'><h3 className='font-semibold'>Pending & Recent Leaves</h3><div className='mt-3 space-y-2'>{['CR-1024 Annual Leave','CR-1331 Medical Leave','CR-1420 Recurrent Training'].map((item,idx)=><div key={item} className='flex items-center justify-between rounded-xl bg-slate-800/80 p-3 text-sm'><span>{item}</span><Badge tone={idx===0?'yellow':idx===1?'green':'blue'}>{idx===0?'Pending':idx===1?'Approved':'In Review'}</Badge></div>)}</div></Card></div>}

export function ConflictsPage(){return <div className='space-y-3'>{alerts.map((a)=><Card key={a.id} className='p-4'><div className='flex justify-between'><p>{a.title}</p><Badge tone={a.severity==='critical'?'red':a.severity==='warning'?'yellow':'blue'}>{a.severity}</Badge></div></Card>)}</div>}

export function AssignmentsPage(){const [columns,setColumns]=useState({available:crewMembers.map((c)=>c.name),assigned:['SQ224 JFK-LHR','EK201 DXB-CDG']}); const onDragEnd=(result)=>{if(!result.destination) return; const source=[...columns[result.source.droppableId]]; const [moved]=source.splice(result.source.index,1); const dest=[...columns[result.destination.droppableId]]; dest.splice(result.destination.index,0,moved); setColumns({...columns,[result.source.droppableId]:source,[result.destination.droppableId]:dest});}; return <DragDropContext onDragEnd={onDragEnd}><div className='grid gap-4 lg:grid-cols-2'>{Object.keys(columns).map((key)=><Droppable key={key} droppableId={key}>{(provided)=><Card className='p-4'><div ref={provided.innerRef} {...provided.droppableProps}><h3 className='font-semibold mb-3'>{key==='available'?'Available Crew Pool':'Assigned Shift Blocks'}</h3>{columns[key].map((it,i)=><Draggable key={it} draggableId={it} index={i}>{(p)=><div ref={p.innerRef} {...p.draggableProps} {...p.dragHandleProps} className='mb-2 rounded-xl bg-slate-800 p-3 text-sm'>{it}</div>}</Draggable>)}{provided.placeholder}</div></Card>}</Droppable>)}</div></DragDropContext>}

export function CompliancePage(){return <Card className='p-4'><h3 className='font-semibold'>Compliance Control Panel</h3><div className='mt-3 space-y-2'>{['Max 100 duty hours in 28 days','Minimum 12-hour rest after long-haul','License and type-rating validity check'].map((rule,idx)=><div key={rule} className='flex justify-between rounded-xl bg-slate-800 p-3 text-sm'><span>{rule}</span><Badge tone={idx===2?'yellow':'green'}>{idx===2?'Due Soon':'Compliant'}</Badge></div>)}</div></Card>}

export function AdminPage(){return <Card className='p-4'><h3 className='font-semibold'>Admin Management</h3><div className='mt-3 flex gap-2'><Button variant='secondary'>Crew</Button><Button variant='secondary'>Leaves</Button><Button variant='secondary'>Reports</Button></div><div className='mt-4 grid gap-3 md:grid-cols-3'>{['Crew registry sync complete','6 leave approvals pending','Monthly utilization report generated'].map((item)=><div key={item} className='rounded-xl bg-slate-800 p-3 text-sm'>{item}</div>)}</div></Card>}
