import { Card,Badge,Button } from '../components/UI';
import { alerts, crew, kpis, utilization } from '../data/mockData';
import { ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,BarChart,Bar } from 'recharts';
import { useMemo, useState } from 'react';
import { DragDropContext,Droppable,Draggable } from 'react-beautiful-dnd';

export const Dashboard=()=> <div className='grid gap-4 md:grid-cols-4'>{kpis.map(k=><Card key={k.title}><p className='text-slate-400 text-sm'>{k.title}</p><h3 className='text-2xl font-bold mt-2'>{k.value}</h3><p className='text-cyan-300 text-xs mt-1'>{k.delta}</p></Card>)}<Card className='md:col-span-2 h-72'><h3 className='mb-3'>Crew Utilization</h3><ResponsiveContainer width='100%' height='90%'><LineChart data={utilization}><XAxis dataKey='day'/><YAxis/><Tooltip/><Line dataKey='utilization' stroke='#22d3ee'/></LineChart></ResponsiveContainer></Card><Card className='md:col-span-2 h-72'><h3 className='mb-3'>Duty Hours</h3><ResponsiveContainer width='100%' height='90%'><BarChart data={utilization}><XAxis dataKey='day'/><YAxis/><Tooltip/><Bar dataKey='hours' fill='#0ea5e9'/></BarChart></ResponsiveContainer></Card><Card className='md:col-span-2'><h3>Recent Activity</h3><ul className='mt-2 space-y-2 text-sm'>{['Roster updated for Intl flights','Captain reassigned to SQ224','Compliance audit completed'].map(t=><li key={t} className='p-2 rounded-lg bg-slate-900/70'>{t}</li>)}</ul></Card><Card className='md:col-span-2'><h3>Alerts Panel</h3><div className='space-y-2 mt-2'>{alerts.map(a=><div key={a.title} className='flex justify-between p-2 bg-slate-900/70 rounded-lg'><span>{a.title}</span><Badge tone={a.severity==='high'?'red':a.severity==='medium'?'yellow':'blue'}>{a.severity}</Badge></div>)}</div></Card></div>;

export const CrewPage=()=>{const [q,setQ]=useState('');const filtered=useMemo(()=>crew.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())),[q]);return <><input placeholder='Search crew' value={q} onChange={e=>setQ(e.target.value)} className='mb-4 bg-slate-900 rounded-xl px-3 py-2 w-full md:w-80'/><div className='grid md:grid-cols-3 gap-4'>{filtered.map(c=><Card key={c.id}><img src={c.photo} className='w-14 h-14 rounded-full'/><h4 className='mt-2 font-semibold'>{c.name}</h4><p className='text-sm text-slate-400'>{c.role} · {c.base}</p><Badge tone={c.status==='On Duty'?'green':c.status==='On Leave'?'red':'yellow'}>{c.status}</Badge><div className='mt-3'><Button variant='ghost'>View Profile</Button></div></Card>)}</div></>};

export const RosterPage=()=> <Card><h3>Weekly Roster View</h3><div className='grid grid-cols-8 gap-2 mt-4 text-xs'>{['Crew','Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(h=><div key={h} className='font-semibold text-cyan-300'>{h}</div>)}{crew.map(c=><><div key={c.id} className='bg-slate-900 p-2 rounded'>{c.name}</div>{Array.from({length:7}).map((_,i)=><div key={c.id+i} className={`p-2 rounded ${i%3===0?'bg-cyan-500/30':i%3===1?'bg-emerald-500/30':'bg-violet-500/30'}`}>{['AM','PM','OFF'][i%3]}</div>)}</>)}</div></Card>;
export const DutyHoursPage=()=> <Card><h3>Duty Hours Tracker</h3>{crew.map((c,i)=>{const p=65+i*12;const tone=p>90?'red':p>80?'yellow':'green';return <div key={c.id} className='mt-4'><div className='flex justify-between'><span>{c.name}</span><Badge tone={tone}>{p>90?'Overlimit':p>80?'Warning':'Safe'}</Badge></div><div className='h-2 bg-slate-800 rounded mt-2'><div className={`h-2 rounded ${tone==='green'?'bg-emerald-400':tone==='yellow'?'bg-amber-400':'bg-red-400'}`} style={{width:`${p}%`}}/></div></div>})}</Card>;
export const LeavePage=()=> <div className='grid md:grid-cols-2 gap-4'><Card><h3>Request Leave</h3><div className='space-y-3 mt-3'><input className='w-full bg-slate-900 rounded-xl p-2' placeholder='Crew ID'/><input type='date' className='w-full bg-slate-900 rounded-xl p-2'/><textarea className='w-full bg-slate-900 rounded-xl p-2' placeholder='Reason'></textarea><Button>Submit Request</Button></div></Card><Card><h3>Leave Requests</h3><div className='mt-2 space-y-2'>{['Amelia - Annual Leave','Sofia - Medical','Noah - Training'].map((l,i)=><div key={l} className='p-2 rounded-lg bg-slate-900 flex justify-between'><span>{l}</span><Badge tone={i===0?'yellow':i===1?'green':'blue'}>{i===0?'Pending':i===1?'Approved':'Review'}</Badge></div>)}</div></Card></div>;
export const ConflictsPage=()=> <div className='space-y-3'>{alerts.map(a=><Card key={a.title}><div className='flex justify-between'><p>{a.title}</p><Badge tone={a.severity==='high'?'red':'yellow'}>{a.severity==='high'?'Critical':'Attention'}</Badge></div></Card>)}</div>;
export const AssignmentsPage=()=>{const [cols,setCols]=useState({pool:crew.map(c=>c.name),shift:['Flight SQ224','Flight EK201']});const onDragEnd=r=>{if(!r.destination)return;const s=[...cols[r.source.droppableId]];const [m]=s.splice(r.source.index,1);const d=[...cols[r.destination.droppableId]];d.splice(r.destination.index,0,m);setCols({...cols,[r.source.droppableId]:s,[r.destination.droppableId]:d});};return <DragDropContext onDragEnd={onDragEnd}><div className='grid md:grid-cols-2 gap-4'>{Object.keys(cols).map(k=><Droppable droppableId={k} key={k}>{p=><Card ref={p.innerRef} {...p.droppableProps}><h3 className='capitalize'>{k==='pool'?'Available Crew':'Assigned Shift'}</h3>{cols[k].map((item,i)=><Draggable draggableId={item} index={i} key={item}>{pp=><div ref={pp.innerRef} {...pp.draggableProps} {...pp.dragHandleProps} className='mt-2 p-2 bg-slate-900 rounded-lg'>{item}</div>}</Draggable>)}{p.placeholder}</Card>}</Droppable>)}</div></DragDropContext>};
export const CompliancePage=()=> <Card><h3>Compliance Rules</h3><div className='mt-3 space-y-2'>{['Max 100 duty hours / 28 days','Min 12-hour rest after long-haul','Type-rating validity required'].map((r,i)=><div key={r} className='p-3 bg-slate-900 rounded-lg flex justify-between'><span>{r}</span><Badge tone={i===2?'yellow':'green'}>{i===2?'Expiring Soon':'Compliant'}</Badge></div>)}</div></Card>;
export const AdminPage=()=> <Card><h3>Admin Panel</h3><div className='flex gap-2 mt-3'>{['Crew','Leaves','Reports'].map(t=><Button key={t} variant='ghost'>{t}</Button>)}</div><div className='grid md:grid-cols-3 gap-3 mt-4'>{['Crew records synchronized','5 leave requests pending','Monthly ops report ready'].map(i=><div key={i} className='p-3 bg-slate-900 rounded-lg'>{i}</div>)}</div></Card>;
